name: GitHub Actions Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."git
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run Continuous Integration
        run: npm ci
      - name: Run Build
        run: npm run build --if-present
      - run: echo "🍏 This job's status is ${{ job.status }}."
